# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/dmadesign/dmadesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign || ORIG_REF_NAME==dmadesign} -quiet] -quiet

# IP: bd/dmadesign/ip/dmadesign_zynq_ultra_ps_e_0_0/dmadesign_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==dmadesign_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/dmadesign/ip/dmadesign_axi_dma_0_0/dmadesign_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign_axi_dma_0_0 || ORIG_REF_NAME==dmadesign_axi_dma_0_0} -quiet] -quiet

# IP: bd/dmadesign/ip/dmadesign_xlconcat_0_0/dmadesign_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign_xlconcat_0_0 || ORIG_REF_NAME==dmadesign_xlconcat_0_0} -quiet] -quiet

# IP: bd/dmadesign/ip/dmadesign_axis_data_fifo_0_0/dmadesign_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign_axis_data_fifo_0_0 || ORIG_REF_NAME==dmadesign_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/dmadesign/ip/dmadesign_ps8_0_axi_periph_0/dmadesign_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign_ps8_0_axi_periph_0 || ORIG_REF_NAME==dmadesign_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/dmadesign/ip/dmadesign_rst_ps8_0_99M_0/dmadesign_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign_rst_ps8_0_99M_0 || ORIG_REF_NAME==dmadesign_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/dmadesign/ip/dmadesign_axi_smc_0/dmadesign_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign_axi_smc_0 || ORIG_REF_NAME==dmadesign_axi_smc_0} -quiet] -quiet

# IP: bd/dmadesign/ip/dmadesign_auto_ds_0/dmadesign_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign_auto_ds_0 || ORIG_REF_NAME==dmadesign_auto_ds_0} -quiet] -quiet

# IP: bd/dmadesign/ip/dmadesign_auto_pc_0/dmadesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmadesign_auto_pc_0 || ORIG_REF_NAME==dmadesign_auto_pc_0} -quiet] -quiet

# XDC: bd/dmadesign/dmadesign_ooc.xdc
