// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_ddr_hls_test (
volatile int* start_signal,
volatile int* hls_check,
volatile int* num,
long long unsigned int* saMaster);
