# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/zedboard_base_axi_smc_1.xci
# IP: The module: 'zedboard_base_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/bd_b7bb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_5/bd_b7bb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_11/bd_b7bb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_12/bd_b7bb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_6/bd_b7bb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_7/bd_b7bb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_8/bd_b7bb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_9/bd_b7bb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_10/bd_b7bb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_2/bd_b7bb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_3/bd_b7bb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_4/bd_b7bb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_0/bd_b7bb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_1/bd_b7bb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_5/bd_b7bb_s00a2s_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_11/bd_b7bb_m00s2a_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_6/bd_b7bb_sarn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_7/bd_b7bb_srn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_8/bd_b7bb_sawn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_9/bd_b7bb_swn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_10/bd_b7bb_sbn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_1/bd_b7bb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_1/bd_b7bb_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/zedboard_base_axi_smc_1.xci
# IP: The module: 'zedboard_base_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/bd_b7bb.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_5/bd_b7bb_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_11/bd_b7bb_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_12/bd_b7bb_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_6/bd_b7bb_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_7/bd_b7bb_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_8/bd_b7bb_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_9/bd_b7bb_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_10/bd_b7bb_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_2/bd_b7bb_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_3/bd_b7bb_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_4/bd_b7bb_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_0/bd_b7bb_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_1/bd_b7bb_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_5/bd_b7bb_s00a2s_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_11/bd_b7bb_m00s2a_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_6/bd_b7bb_sarn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_7/bd_b7bb_srn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_8/bd_b7bb_sawn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_9/bd_b7bb_swn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_10/bd_b7bb_sbn_0_ooc.xdc

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_1/bd_b7bb_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_1/bd_b7bb_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
