# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zedboard_base/zedboard_base.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base || ORIG_REF_NAME==zedboard_base} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_ddr_hls_test_0_0/zedboard_base_ddr_hls_test_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_ddr_hls_test_0_0 || ORIG_REF_NAME==zedboard_base_ddr_hls_test_0_0} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_zynq_ultra_ps_e_0_0/zedboard_base_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==zedboard_base_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_ps8_0_axi_periph_0/zedboard_base_ps8_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_ps8_0_axi_periph_0 || ORIG_REF_NAME==zedboard_base_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_rst_ps8_0_99M_0 || ORIG_REF_NAME==zedboard_base_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_axi_smc_1/zedboard_base_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_axi_smc_1 || ORIG_REF_NAME==zedboard_base_axi_smc_1} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_xbar_1/zedboard_base_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_xbar_1 || ORIG_REF_NAME==zedboard_base_xbar_1} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_auto_ds_1/zedboard_base_auto_ds_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_auto_ds_1 || ORIG_REF_NAME==zedboard_base_auto_ds_1} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_auto_pc_1/zedboard_base_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_auto_pc_1 || ORIG_REF_NAME==zedboard_base_auto_pc_1} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_auto_ds_0/zedboard_base_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_auto_ds_0 || ORIG_REF_NAME==zedboard_base_auto_ds_0} -quiet] -quiet

# IP: bd/zedboard_base/ip/zedboard_base_auto_pc_0/zedboard_base_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_base_auto_pc_0 || ORIG_REF_NAME==zedboard_base_auto_pc_0} -quiet] -quiet

# XDC: bd/zedboard_base/zedboard_base_ooc.xdc
