# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.cache/wt [current_project]
set_property parent.project_path /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.2 [current_project]
set_property ip_repo_paths {
  /home/guan/Xilinx/Project/ip_repo/axi_test_1.0
  /home/guan/Xilinx/Project/test/prj/solution1
} [current_project]
set_property ip_output_repo /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/hdl/zedboard_base_wrapper.v
add_files /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/zedboard_base.bd
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_ddr_hls_test_0_0/constraints/ddr_hls_test_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_zynq_ultra_ps_e_0_0/zedboard_base_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_zynq_ultra_ps_e_0_0/zedboard_base_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_5/bd_b7bb_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_11/bd_b7bb_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_6/bd_b7bb_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_7/bd_b7bb_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_8/bd_b7bb_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_9/bd_b7bb_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_10/bd_b7bb_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_1/bd_b7bb_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/bd_0/ip/ip_1/bd_b7bb_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_xbar_1/zedboard_base_xbar_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_ds_1/zedboard_base_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_ds_1/zedboard_base_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_ds_1/zedboard_base_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_pc_1/zedboard_base_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_ds_0/zedboard_base_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_ds_0/zedboard_base_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_ds_0/zedboard_base_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_auto_pc_0/zedboard_base_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/zedboard_base_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top zedboard_base_wrapper -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zedboard_base_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zedboard_base_wrapper_utilization_synth.rpt -pb zedboard_base_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
