# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0.xci
# IP: The module: 'zedboard_base_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0.xci
# IP: The module: 'zedboard_base_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/guan/Xilinx/Project/HLS_DDR/HLS_DDR.srcs/sources_1/bd/zedboard_base/ip/zedboard_base_rst_ps8_0_99M_0/zedboard_base_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zedboard_base_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
